Failure # 1 (occurred at 2020-07-27_13-06-26)
Traceback (most recent call last):
  File "/Users/tobias.sunderdiek/ri/vortrag_tune/demo-venv/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 467, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/Users/tobias.sunderdiek/ri/vortrag_tune/demo-venv/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 431, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/Users/tobias.sunderdiek/ri/vortrag_tune/demo-venv/lib/python3.7/site-packages/ray/worker.py", line 1517, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

